cluster:
  name: es-cluster
  initial_master_nodes: [ "es-cluster-node1","es-cluster-node2","es-cluster-node3" ]
node:
  master: true
  data: true
network:
  bind_host: 0.0.0.0
http:
  port: 9200
  cors:
    enabled: true
    allow-origin: "*"
transport.tcp.port: 9300
discovery:
  seed_hosts:
    - es1
  zen:
    minimum_master_nodes: 2
bootstrap:
  memory_lock: false
  system_call_filter: false