version: "3.9"

services:
  zoo1:
    image: liubin/zookeeper
    build: .
    container_name: zoo1
    volumes:
      - ./config/zoo.cfg:/conf/zoo.cfg
      # 通过在数据目录中查找文件myid来知道它是哪个服务器。该文件包含 ASCII 格式的服务器编号
      - ./config/myid1:/data/myid
  zoo2:
    image: liubin/zookeeper
    container_name: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: liubin/zookeeper
    container_name: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

networks:
  default:
    external:
      name: liubin-bridge