FROM openjdk:8-jre-alpine
# settings timezone
ENV TZ Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN addgroup -S spring && adduser -S spring -G spring
RUN mkdir /logs && chown spring:spring /logs
RUN mkdir /app && chown spring:spring /app
USER spring:spring

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["sh","-c","java ${JAVA_OPTS} -cp app:app/lib/* com.example.demobatch.DemoBatchApplication"]