version: "3.9"

services:
  mysql_master:
    image: liubin/mysql
    build: .
    container_name: mysql_master
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./master.cnf:/etc/mysql/my.cnf:ro
      - /var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=ZAQ!2wsx
      - MYSQL_DATABASE=demo
  mysql_slave:
    image: liubin/mysql
    container_name: mysql_slave
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: bind
        source: ./slave.cnf
        target: /etc/mysql/my.cnf
        read_only: true
      - /var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=ZAQ!2wsx
      - MYSQL_DATABASE=demo

networks:
  default:
    external:
      name: liubin-bridge
