version: "3.9"

services:
  redis2:
    image: liubin/redis
    build: .
    container_name: redis2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.2
  redis3:
    image: liubin/redis
    container_name: redis3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.3
  redis4:
    image: liubin/redis
    container_name: redis4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.4

  redis5:
    image: liubin/redis
    container_name: redis5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.5
  redis6:
    image: liubin/redis
    container_name: redis6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.6
  redis7:
    image: liubin/redis
    container_name: redis7
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.7

  redis8:
    image: liubin/redis
    container_name: redis8
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.8
  redis9:
    image: liubin/redis
    container_name: redis9
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.9
  redis10:
    image: liubin/redis
    container_name: redis10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      liubin-bridge:
        ipv4_address: 172.18.0.10

networks:
  liubin-bridge:
    external: true